import { Post } from '../../modules/shared/interfaces/post.interface';

export const POSTS_LIST: Post[] = [
  {
    id: 0,
    title: 'Lorem Lorem Lorem ipsum dolor sit amet. Illum, quaerat.',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    author: 'Agatha Christie',
    avatar: 'account_box',
    likes: 333,
    date: '28 Nov, 2021',
    tags: ['some', 'else', 'tags', 'article', 'sunshine'],
  },
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet. Illum, quaerat.',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    author: 'Agatha Christie',
    avatar: 'account_box',
    likes: 0,
    date: '28 Nov, 2021',
    tags: ['some', 'else', 'tags', 'article', 'sunshine'],
  },
  {
    id: 2,
    title: 'Lorem ipsum dolor sit amet. Illum, quaerat.',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    author: 'Agatha Christie',
    avatar: 'perm_identity',
    likes: 1,
    date: '28 Nov, 2021',
  },
  {
    id: 3,
    title: 'Lorem ipsum dolor sit amet. Illum, quaerat.',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    author: 'Agatha Christie',
    avatar: 'self_improvement',
    likes: 2,
    date: '28 Nov, 2021',
  },
  {
    id: 4,
    title: 'Lorem ipsum dolor sit amet. Illum, quaerat.',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    author: 'Agatha Christie',
    avatar: 'engineering',
    likes: 2,
    date: '28 Nov, 2021',
  },
  {
    id: 5,
    title: 'Lorem ipsum dolor sit amet. Illum, quaerat.',
    subtitle: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, quaerat.',
    author: 'Agatha Christie',
    avatar: 'perm_identity',
    likes: 10000,
    date: '28 Nov, 2021',
  },
];
